<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT6COfFA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT6COfFA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT6COfFA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT6COfFA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerT6COfFA\App_KernelDevDebugContainer([
    'container.build_hash' => 'T6COfFA',
    'container.build_id' => '9ec669db',
    'container.build_time' => 1747340035,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT6COfFA');
