<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPYU4aTf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPYU4aTf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPYU4aTf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPYU4aTf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPYU4aTf\App_KernelDevDebugContainer([
    'container.build_hash' => 'PYU4aTf',
    'container.build_id' => '2a4b32f5',
    'container.build_time' => 1745788998,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPYU4aTf');
