<?php

namespace ContainerT6COfFA;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4B7UExzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4B7UExz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4B7UExz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'triangleRepository' => ['privates', 'App\\Repository\\TriangleRepository', 'getTriangleRepositoryService', true],
        ], [
            'em' => '?',
            'triangleRepository' => 'App\\Repository\\TriangleRepository',
        ]);
    }
}
