<?php

namespace ContainerT6COfFA;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GIfda8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._GIfda8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._GIfda8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'triangleRepository' => ['privates', 'App\\Repository\\TriangleRepository', 'getTriangleRepositoryService', true],
        ], [
            'triangleRepository' => 'App\\Repository\\TriangleRepository',
        ]);
    }
}
