<?php

namespace ContainerT6COfFA;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Iy3nvqmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iy3nvqm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iy3nvqm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\TriangleController::addTriangle' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\TriangleController::editTriangle' => ['privates', '.service_locator.4B7UExz', 'get_ServiceLocator_4B7UExzService', true],
            'App\\Controller\\TriangleController::getAllTriangles' => ['privates', '.service_locator._GIfda8', 'get_ServiceLocator_GIfda8Service', true],
            'App\\Controller\\TriangleController::getSummary' => ['privates', '.service_locator.1AnUItw', 'get_ServiceLocator_1AnUItwService', true],
            'App\\Controller\\TriangleController::getTriangleById' => ['privates', '.service_locator._GIfda8', 'get_ServiceLocator_GIfda8Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\TriangleController:addTriangle' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\TriangleController:editTriangle' => ['privates', '.service_locator.4B7UExz', 'get_ServiceLocator_4B7UExzService', true],
            'App\\Controller\\TriangleController:getAllTriangles' => ['privates', '.service_locator._GIfda8', 'get_ServiceLocator_GIfda8Service', true],
            'App\\Controller\\TriangleController:getSummary' => ['privates', '.service_locator.1AnUItw', 'get_ServiceLocator_1AnUItwService', true],
            'App\\Controller\\TriangleController:getTriangleById' => ['privates', '.service_locator._GIfda8', 'get_ServiceLocator_GIfda8Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\TriangleController::addTriangle' => '?',
            'App\\Controller\\TriangleController::editTriangle' => '?',
            'App\\Controller\\TriangleController::getAllTriangles' => '?',
            'App\\Controller\\TriangleController::getSummary' => '?',
            'App\\Controller\\TriangleController::getTriangleById' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\TriangleController:addTriangle' => '?',
            'App\\Controller\\TriangleController:editTriangle' => '?',
            'App\\Controller\\TriangleController:getAllTriangles' => '?',
            'App\\Controller\\TriangleController:getSummary' => '?',
            'App\\Controller\\TriangleController:getTriangleById' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
